### ISSUE TITLE
Can you provide a new DisplayMode

### ISSUE THREAD

**Issue by danieltigse** [niqdev/ipcam-view#23]
Please I need a new DisplayMode. In ImageView it is called centerCrop, when the image is cropped until fit in the screen without losing proportionality.

**Comment by niqdev** [comment]
Hi,
the value available are [here](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/DisplayMode.java) and they are use [here](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/MjpegViewDefault.java#L55)

In order to add a new `DisplayMode` I need that you provide me some info or the implementation for the method `MjpegViewThread#destRect`. I have no idea how to calculate it or which values of `dispWidth dispHeight bmw bmh` correspond to `centerCrop`.

By the way, would be nice if you use this library if you link your project on github or on the playstore in the readme

**Comment by niqdev** [comment]
@danieltigse did you manage to handle the DisplayMode? Otherwise I will close the issue.
Thanks

**Comment by danieltigse** [comment]
No, I leave it in that way thanks. Close it.
