### ISSUE TITLE
MjpegInputStreamDefault  is not public~

### ISSUE THREAD

**Issue by SoyaLeaf** [niqdev/ipcam-view#51]
```
Socket socket = new Socket(ip, port);
InputStream in = socket.getInputStream();
MjpegInputStreamDefault mjpegInputStreamDefault = new MjpegInputStreamDefault(this);
mjpegInputStreamDefault.readMjpegFrame();
```

我目前需要通过这种方式来使用，可是您的库目前不支持。是否可以考虑 MjpegInputStreamDefault 类开放为public？

**Comment by niqdev** [comment]
English please!

**Comment by SoyaLeaf** [comment]
I'm so sorry ~ and I'm not good at English...
and then... the following content from Google Translate... :(
```
Socket socket = new Socket(ip, port);
InputStream in = socket.getInputStream();
MjpegInputStreamDefault mjpegInputStreamDefault = new MjpegInputStreamDefault(this);
mjpegInputStreamDefault.readMjpegFrame();
```
I currently need to use this method, but your library is not currently supported. Is it possible to consider that the MjpegInputStreamDefault class is open for public?

**Comment by niqdev** [comment]
no problem for the translation

In theory is meant not to be accessible by design and used only by the lib, one easy solution is to have a package in your project called `com.github.niqdev.mjpeg` where you extend `MjpegInputStreamDefault` and add your logic, otherwise you could make a pull request, so that you can test your changes before I release a new version

Thanks

**Comment by SoyaLeaf** [comment]
I got it~thank u very much.
