### ISSUE TITLE
Upgrade to android-studio v3

### ISSUE THREAD

**Issue by niqdev** [niqdev/ipcam-view#57]

**Comment by amadeu01** [comment]
Hi @niqdev 

How are you doing?

Here at the branch [/feature/studio-v3](https://github.com/niqdev/ipcam-view/tree/feature/studio-v3)  we have a problem:
1. We are `forcing` the user of the library use Rx, due to the open what returns an `Observable` object. In other words, the user has to use the library.
2. We can use  `api` keyword from Gradle 3.x android plugin. [More info](https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa)


So, my question is: Would we let the user `gain` the Rx Library together with the `ipcam-view`? Or, Will the user be obligated to import Rx Library so they can use the library. I do not know if when you import a dependency library from another library, if it gives any trouble, perhaps the user just have to exclude the dependency he/she does not want. [More info, dependency conflict ](https://medium.com/mindorks/avoiding-conflicts-in-android-gradle-dependencies-28e4200ca235)

**Comment by niqdev** [comment]
Thanks @amadeu01
