### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amadeu01** [niqdev/ipcam-view#61]
@niqdev 

I was looking at the code. And, I could not understand how you update the Mjpeg view from other thread (other than UI thread). I do not know if I got it right, but it seems that you load a bitmap from a thread that is created on `MjepgView` and update that bitmap on the `MjpegView` from other thread. But, I always listened that we could only update something on the UI by using the UI thread. So, how can I update something on the UI, like change images for one `ImageView` without interrupt UI and/or without having to use UI thread?

**Comment by niqdev** [comment]
It's been a long time that I don't touch that code, but if I understand it correctly your question, it could be the combination of `Scheduler.io` and `AndroidSchedulers.mainThread`. I can suggest to have a look also at the original code, I think there is a link in the readme and use the current best practices without looking to much at rx-java.
Also another idea that I had in mind when I wrote the lib initially, was to have a multi project that might include different lib for different video streaming format, that's why I kept separate the project name from the lib name.

**Comment by amadeu01** [comment]
I think this two articles kind of response my question hahaha

- [Painless Threading](https://android-developers.googleblog.com/2009/05/painless-threading.html)
- [Universal Image Loader](https://medium.com/@ssaurel/enjoy-the-power-of-universal-image-loader-to-load-easily-your-images-on-android-3b36aa8a3161)

**Comment by niqdev** [comment]
Thanks for sharing, shall I close this issue?

**Comment by amadeu01** [comment]
@niqdev Yeah, absolutely. Thanks for your support 😄
